In [1]:
import pandas as pd
labels_train = pd.read_csv('labels_training_set.csv')
eventos=pd.read_csv('events_up_to_01062018.csv')
labels_test=pd.read_csv('trocafone_kaggle_test.csv')
#labels_train.head()

/home/jorge/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
#eventos.head()

In [3]:
eventos['timestamp']=pd.to_datetime(eventos['timestamp'])

In [4]:
#eventos['timestamp']=eventos[eventos['timestamp'].dt.month==5]

In [33]:
eventos2=eventos.copy()
#tomo los 100 modelos mas populares
modelos_populares=eventos2[eventos2['event']=='conversion'].groupby(['model'])['model'].count().rename('cuenta').sort_values(ascending=False).reset_index().head(100).model.tolist()
#type(modelos_populares)
modelos_populares

['Samsung Galaxy J5',
 'iPhone 5s',
 'iPhone 6',
 'iPhone 6S',
 'Motorola Moto G2 3G Dual',
 'Samsung Galaxy J7 Prime',
 'Motorola Moto G4 Plus',
 'Samsung Galaxy S7',
 'Samsung Galaxy S6 Flat',
 'Samsung Galaxy S7 Edge',
 'Samsung Galaxy J7',
 'iPhone 4S',
 'Samsung Galaxy S8',
 'iPhone 5c',
 'iPhone 7 Plus',
 'iPhone 6 Plus',
 'Samsung Galaxy J2 Prime TV',
 'Samsung Galaxy S6 Edge',
 'Samsung Galaxy A5 2017',
 'Samsung Galaxy S5',
 'Samsung Galaxy Gran Prime Duos TV',
 'Samsung Galaxy A5',
 'Samsung Galaxy Win Duos',
 'iPhone 7',
 'Lenovo Vibe K5',
 'Motorola Moto G3 4G',
 'iPhone 5',
 'Samsung Galaxy J2 4G Duos TV',
 'iPhone SE',
 'Samsung Galaxy S5 Duos',
 'Motorola Moto G5 Plus',
 'Samsung Galaxy S5 Mini Duos',
 'Samsung Galaxy J1 Mini',
 'Samsung Galaxy Core Plus Duos TV',
 'Motorola Moto G5 ',
 'Samsung Galaxy J7 2016 Metal',
 'Samsung Galaxy A5 2016',
 'iPhone 4G',
 'iPhone 6S Plus',
 'Samsung Galaxy J3']

In [34]:
eventos_onehot = eventos[['person','event','model']].copy()
#hago un one hot encoding de la columna event
eventos_onehot = pd.get_dummies(eventos_onehot ,columns=['event'],prefix=[''],prefix_sep='')

#filtro los datos que contengan alguno de los modelos populares 
eventos_onehot=eventos_onehot[eventos_onehot['model'].apply(lambda x: x in modelos_populares)]
#hago un one hot encoding de la columna model
eventos_onehot = pd.get_dummies(eventos_onehot ,columns=['model'],prefix='',prefix_sep='')
#hago la suma de la cantidad de eventos por persona
eventos_sum=eventos_onehot.groupby(['person']).sum().reset_index()

eventos_sum.describe()

,checkout,conversion,lead,viewed product,Lenovo Vibe K5,Motorola Moto G2 3G Dual,Motorola Moto G3 4G,Motorola Moto G4 Plus,Motorola Moto G5,Motorola Moto G5 Plus,...,iPhone 5,iPhone 5c,iPhone 5s,iPhone 6,iPhone 6 Plus,iPhone 6S,iPhone 6S Plus,iPhone 7,iPhone 7 Plus,iPhone SE
count,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,...,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000,35852.000000
mean,1.467003,0.151651,0.014504,26.450993,0.206293,0.286595,0.334263,0.704675,0.312284,0.384246,...,0.517433,0.781212,2.828266,2.991800,0.899615,2.711899,1.059132,1.645403,1.257029,1.032913
std,2.439665,0.895762,0.230965,64.571343,2.139264,2.316991,2.677688,6.510446,1.991990,2.689332,...,3.664297,6.116444,13.215458,12.176021,6.453974,14.146708,8.267417,8.401545,7.310597,8.188627
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,0.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,173.000000,113.000000,23.000000,2154.000000,147.000000,148.000000,185.000000,361.000000,76.000000,134.000000,...,206.000000,354.000000,836.000000,607.000000,500.000000,683.000000,624.000000,460.000000,335.000000,557.000000

In [35]:
# preprwaro los dataframe de entrenamiento de testeo
eventos_train=labels_train.merge(eventos_sum,how='left',on='person').fillna(0)
eventos_test=labels_test.merge(eventos_sum,how='left',on='person').fillna(0)
eventos_train.describe()

,label,checkout,conversion,lead,viewed product,Lenovo Vibe K5,Motorola Moto G2 3G Dual,Motorola Moto G3 4G,Motorola Moto G4 Plus,Motorola Moto G5,...,iPhone 5,iPhone 5c,iPhone 5s,iPhone 6,iPhone 6 Plus,iPhone 6S,iPhone 6S Plus,iPhone 7,iPhone 7 Plus,iPhone SE
count,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,...,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000,19414.000000
mean,0.050479,1.344133,0.139178,0.011435,24.567529,0.180179,0.285052,0.330638,0.628670,0.278150,...,0.495364,0.718348,2.670444,2.692284,0.815649,2.509426,1.002266,1.541156,1.150149,0.945761
std,0.218937,2.181341,0.631589,0.193313,65.122240,1.754049,2.544474,2.939566,5.539405,1.785978,...,3.970809,5.553679,14.434935,11.243395,5.267487,14.176616,8.178619,8.619693,7.133390,7.880913
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,52.000000,30.000000,16.000000,2154.000000,69.000000,148.000000,185.000000,341.000000,56.000000,...,206.000000,191.000000,836.000000,607.000000,212.000000,683.000000,344.000000,460.000000,335.000000,557.000000

In [62]:
#guardo los features
#features=eventos_train.drop(['person' , 'label','checkout','conversion','lead','viewed product'] , axis='columns').columns
features2=['checkout','conversion','lead','viewed product']
#guardo los features
features=eventos_train.drop(['person' , 'label'] , axis='columns').columns

In [63]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
y = eventos_train['label']
predictor_cols = features
 

# Create training predictors data
X = eventos_train[predictor_cols]
seed = 0
test_size = 0.5
train_X, X_test, train_y, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
#model = XGBClassifier()
xgb_model=xgb.XGBClassifier(max_depth=4, n_estimators=300,eta=0.05 ,colsample_bytree=0.3,gamma=6,subsample=1,learning_rate=0.06,objective='binary:logistic')
xgb_model.fit(train_X, train_y)

scores = cross_val_score(xgb_model,train_X, train_y, scoring="roc_auc", cv=3)
scores.mean()

0.7627807506066336

In [64]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

y= eventos_train['label']
predictor_cols = features2
 

# Create training predictors data
X = eventos_train[predictor_cols]

GBC = GradientBoostingClassifier(random_state=1,learning_rate=0.06,subsample=0.6, min_samples_split=3)
scores = cross_val_score(GBC , X, y, scoring="roc_auc", cv=3)
scores.mean()

0.7742047748154928

In [65]:
from sklearn.ensemble import VotingClassifier
vc=VotingClassifier(estimators=[('xgb',xgb_model),('GBC',GBC)],voting='soft')
scores = cross_val_score(vc, train_X, train_y, scoring="roc_auc", cv=4)
print(scores.mean())

0.7634560469247916

In [66]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# pull data into target (y) and predictors (X)
train_y = eventos_train['label']
predictor_cols = features

# Create training predictors data
train_X = eventos_train[predictor_cols]

#my_model = RandomForestRegressor()

#Create a Gaussian Classifier
rf_model =RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)



rf_model.fit(train_X, train_y)
scores = cross_val_score(rf_model, train_X, train_y, scoring="roc_auc", cv=4)
print(scores.mean())

0.7240950726661217

In [14]:
from pandas import Series

test_X = eventos_test[features]
# calculo las predicciones
predicted_labels = xgb_model.predict_proba(test_X)
print(predicted_labels)
# armo el dataframe con las columnas person y label
df_prediction=pd.DataFrame(columns= {'person'},data=eventos_test.person)
df_prediction['label']=0
df_prediction['label']=predicted_labels

[[0.9318508  0.0681492 ]
 [0.8722241  0.12777594]
 [0.73095083 0.2690492 ]
 ...
 [0.8776316  0.12236841]
 [0.8704147  0.12958533]
 [0.98617554 0.01382446]]

       person     label
0    00091926  0.931851
1    00091a7a  0.872224
2    000ba417  0.730951
3    000e4d9e  0.937121
4    000e619d  0.979611
5    001001be  0.896633
6    0010e89a  0.986482
7    0016c4b5  0.986482
8    001804a2  0.951504
9    001a2273  0.987210
10   00202cdb  0.968382
11   0022965d  0.960581
12   0027574e  0.940218
13   00295d74  0.969638
14   002aea56  0.914423
15   002ed810  0.936108
16   002fb981  0.982469
17   00344873  0.982617
18   0038a117  0.944912
19   003a05bf  0.945031
20   00408349  0.872224
21   0041fec6  0.976859
22   0043a48e  0.927840
23   00546f4c  0.891085
24   00556ee5  0.982469
25   0059a996  0.874350
26   005af223  0.979910
27   005e06ef  0.876601
28   0061cbe8  0.872224
29   006549da  0.964874
..        ...       ...
170  0270a59f  0.975538
171  027870af  0.922954
172  027b809f  0.966430
173  027cb5c9  0.982617
174  027e9637  0.982407
175  0280a93d  0.903993
176  028d0864  0.872224
177  02973cb9  0.986482
178  0297fc1e  0.950714
179  029889eb  0.928579
180  029a5c8b  0.987520
181  029e25de  0.986482
182  02a14ee3  0.982049
183  02a9fd4c  0.918334
184  02aa0266  0.986482
185  02b10e44  0.870415
186  02b13444  0.986265
187  02b51109  0.862353
188  02ba6bb6  0.986265
189  02bf0143  0.982617
190  02c2eb63  0.986439
191  02c66b97  0.872224
192  02c73278  0.986265
193  02d42846  0.983115
194  02d80cb2  0.979387
195  02de19f7  0.986265
196  02e1a150  0.874350
197  02e465f4  0.936132
198  02e59a44  0.869519
199  02e65ce8  0.981385

[200 rows x 2 columns]

In [80]:
df2.to_csv('TrocsubmissionJa2.csv', index=False)